name: rust-flying-ninja
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/flying_ninja/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-flying-ninja-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-flying-ninja-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Hello Darwin
        run: |
          dfx start --background
          pushd rust/flying_ninja
          make test
          popd
  rust-flying-ninja-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Hello Linux
        run: |
          dfx start --background
          pushd rust/flying_ninja
          make test
          popd
